'use strict';mix_d("PrimeAcquisitionCXCards__pin-flyout-desktop-card:pin-flyout-desktop-card__0Bz1iUC6",["exports","tslib","@c/scoped-dom","@c/aui-untrusted-ajax","@c/logger"],function(x,g,B,C,D){function v(e){return e&&"object"===typeof e&&"default"in e?e:{"default":e}}function y(e,c){return g.__awaiter(this,void 0,void 0,function(){var a;return g.__generator(this,function(d){try{return a={accepts:"application/json",contentType:"application/json;charset=UTF-8",additionalHeaders:E({})},[2,F["default"].post(c,
a,e).then(function(b){(b=b.responseBody.payload.requestSuccess)||m["default"].log("Request the customer name ajax failed","ERROR");return b}).catch(function(b){m["default"].log("An error occurred while publishing metrics",b);return!1})]}catch(b){m["default"].log("Request the customer name ajax failed with the error:"+b,"ERROR")}return[2,!1]})})}function E(e){var c=(c=z["default"].cardRoot.querySelector("meta[name='anti-csrftoken-a2z']"))?c.getAttribute("content"):"";e["anti-csrftoken-a2z"]=c;return e}
var z=v(B),F=v(C),m=v(D),r;(r||(r={})).Count="Count";var G=function(){function e(c){this.endpoint=c.endpoint}e.prototype.publishImpressionMetric=function(c,a,d){var b=r.Count;a=this.getStandardEventData(c,a,d);null===a?m["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):this.publishMetric("Impression",1,b,a,c,this.endpoint)};e.prototype.publishButtonClickMetric=function(c,a){var d=this,b=r.Count,f=this.getStandardEventData(c,a);null===f?m["default"].log("Event data is null and it indicates the DOM associated to the class isn't available",
"WARN"):(a=document.querySelectorAll(".".concat(c," button")),0===a.length?m["default"].log("No buttons found for the given class","WARN"):a.forEach(function(h){h.addEventListener("click",function(){d.publishMetric("ButtonClick",1,b,f,c,d.endpoint)})}))};e.prototype.publishSpecificButtonClickMetric=function(c,a,d,b,f){var h=this,n=r.Count,k=this.getStandardEventData(c,b,f);null===k?m["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):(b=document.querySelector('[class*="'.concat(a,
'"], [id*="').concat(a,'"]')))?b.addEventListener("click",function(){h.publishMetric(d,1,n,k,c,h.endpoint)}):m["default"].log("Button with selector ".concat(a," not found"),"WARN")};e.prototype.publishCustomMetric=function(c,a,d,b){b=this.extractDimensionsForAdditionalEventData(b);b=Object.fromEntries(b);y({metricName:a,metricValue:d,metricUnit:r.Count,dimensions:b,location:c},this.endpoint)};e.prototype.publishMetric=function(c,a,d,b,f,h){b=this.extractDimensions(b);b=Object.fromEntries(b);y({metricName:c,
metricValue:a,metricUnit:d,dimensions:b,location:f},h)};e.prototype.getStandardEventData=function(c,a,d){return(d=document.querySelector('[class^="'.concat(c,'"], [id^="').concat(c,'"]'))||document.querySelector('div[data-csa-c-painter="'.concat(d,'"]')))?(c={cardName:d.getAttribute("data-csa-c-painter")||c,widgetId:d.getAttribute("data-csa-c-widget-id")||"",pageId:d.getAttribute("data-csa-c-page-id")||"",deviceType:d.getAttribute("data-csa-c-device-type")||""},g.__assign(g.__assign({},c),a)):null};
e.prototype.extractDimensions=function(c){var a,d=new Map;try{for(var b=g.__values(Object.entries(c)),f=b.next();!f.done;f=b.next()){var h=g.__read(f.value,2),n=h[0],k=h[1];"string"!==typeof k&&"number"!==typeof k||""===k.toString()||d.set(n,k.toString())}}catch(q){var p={error:q}}finally{try{f&&!f.done&&(a=b.return)&&a.call(b)}finally{if(p)throw p.error;}}return d};e.prototype.extractDimensionsForAdditionalEventData=function(c){var a,d=new Map;try{for(var b=g.__values(Object.entries(c)),f=b.next();!f.done;f=
b.next()){var h=g.__read(f.value,2),n=h[0],k=h[1];"string"!==typeof k&&"number"!==typeof k||""===k.toString()||d.set(n,k.toString())}}catch(q){var p={error:q}}finally{try{f&&!f.done&&(a=b.return)&&a.call(b)}finally{if(p)throw p.error;}}return d};return e}(),u=function(){function e(){this._state=null}e.getInstance=function(){e.instance||(e.instance=new e);return e.instance};e.prototype.extractMetadata=function(c){var a,d,b,f,h,n,k,p,q,w;c=(c.querySelector("[data-csa-c-metadata-map]")||c).getAttribute("data-csa-c-metadata-map");
var A={};if(c)try{var t=JSON.parse(c),l=t.metadataMap?JSON.parse(t.metadataMap):{},H=g.__assign({offerType:null!==(a=l.offerType)&&void 0!==a?a:"NONE",benefitRestrictionType:null!==(d=l.benefitRestrictionType)&&void 0!==d?d:"NONE",offerSegment:null!==(b=l.offerSegment)&&void 0!==b?b:"NONE",feeType:null!==(f=l.feeType)&&void 0!==f?f:"NONE",benefitTier:null!==(h=l.benefitTier)&&void 0!==h?h:"NONE",variantId:null!==(n=l.variantId)&&void 0!==n?n:"NONE",offerListingId:null!==(k=l.offerListingId)&&void 0!==
k?k:"NONE",experimentTagMetadata:null!==(p=l.experimentTagMetadata)&&void 0!==p?p:"NONE"},l.multiplan?{multiplan:l.multiplan}:{}),I={marketingContentCreativeId:null!==(q=t.marketingContentCreativeId)&&void 0!==q?q:"NONE",acquisitionDevice:null!==(w=t.acquisitionDevice)&&void 0!==w?w:"NONE"};A=g.__assign(g.__assign({},H),I)}catch(J){m["default"].log("Error parsing analyticalMetadataMap:"+J,"ERROR")}return A};e.prototype.initialize=function(c,a,d,b){var f=this.extractMetadata(d);d=(d.querySelector("[data-csa-c-widget-id]")||
d).getAttribute("data-csa-c-widget-id")||"";this._state={publisher:new G({endpoint:c}),cardName:a,csaAttributes:f,painterId:b,widgetId:d}};e.prototype.publishImpression=function(c){var a=this.getState();a.publisher.publishImpressionMetric(a.cardName,g.__assign(g.__assign({},a.csaAttributes),c),a.painterId)};e.prototype.publishMetricWithCoreDimensions=function(c,a){void 0===a&&(a=1);var d=this.getState();d.publisher.publishCustomMetric(d.cardName,c,a,{widgetId:d.widgetId,acquisitionDevice:d.csaAttributes.acquisitionDevice||
""})};e.prototype.publishMetricWithVariantOnly=function(c,a){void 0===a&&(a=1);var d=this.getState();d.publisher.publishCustomMetric(d.cardName,c,a,{widgetId:d.widgetId,variantId:this.getVariantId()})};e.prototype.getVariantId=function(){return this.getState().csaAttributes.variantId||""};e.prototype.publishButtonClick=function(c){var a=this.getState();a.publisher.publishButtonClickMetric(a.cardName,g.__assign(g.__assign({},a.csaAttributes),c))};e.prototype.publishSpecificButtonClick=function(c,a,
d){var b=this.getState();b.publisher.publishSpecificButtonClickMetric(b.cardName,c,a,g.__assign(g.__assign({},b.csaAttributes),d),b.painterId)};e.prototype.publishCustomMetric=function(c,a,d){var b=this.getState();b.publisher.publishCustomMetric(b.cardName,c,a,g.__assign(g.__assign({cardName:b.cardName},b.csaAttributes),d))};e.prototype.getState=function(){if(!this._state)throw Error("MetricsService must be initialized before use");return this._state};return e}().getInstance();x._operationNames=[];
x.card=function(){return g.__awaiter(void 0,void 0,void 0,function(){var e;return g.__generator(this,function(c){e=z["default"].cardRoot;u.initialize("/prime-ajax/acquisition/metrics","pin-flyout-desktop-card",e,"pin-flyout-desktop-card");u.publishImpression();u.publishMetricWithCoreDimensions("Impression");u.publishSpecificButtonClick("pin-flyout-cta-button","pin_flyout_cta_click");return[2]})})}});
